#ifndef CONFIGURATION_H_INCLUDED
#define CONFIGURATION_H_INCLUDED


#define LARGEUR_FENETRE (320*2)
#define HAUTEUR_FENETRE (240*2)

#define TITRE_APPLICATION "BOMBERMAN"

#define PRET 0.1
#define LOIN 1000.0
#define ANGLE_VISION 70.0


#endif // CONFIGURATION_H_INCLUDED

